version: 2

sources:
  - name: raw
    description: Raw source tables for Group 8 project
    database: natalia-dw-project
    schema: cis9440_group8_dataset
    tables:
      - name: raw_311_requests
        identifier: raw_nyc_311_dot_and_nypd_data
        description: Raw 311 requests filtered to NYPD and DOT

      - name: raw_motor_vehicle_collisions
        identifier: source_motor_vehicle_collisions
        description: Raw motor vehicle collisions data